package src.Lab11;

public class RandomString {
    private static String randomString(int len, char letterCase) {
        String ans = "";
        int max, min;
        switch (letterCase) {
            case 'u':
            case 'U':
                max = 'Z';
                min = 'A';
                break;
            case 'l':
            case 'L':
                max = 'z';
                min = 'a';
                break;
            default:
                return "";
        }
        for (int i=0;i<len;i++) {
            ans += (char)(min + (int)(Math.random() * ((max - min) + 1)));
        }
        return ans;
    }
    public static void main(String[] args) {
        System.out.printf("Following random string was generated by randomString(10, 'l'): " + randomString(10, 'l') + "\n");
    }
}
